workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never

stages:
  - build
  - deploy

code:
  stage: build
  before_script:
    - echo $CI_COMMIT_REF_NAME
  script:
    - echo "Compiling the code..."
    - "cd /var/www/backend"
    - "sudo -u www-data git fetch --all"
    - "sudo -u www-data git reset --hard 'origin/dev'"
    - "sudo -u www-data yarn"
    - "sudo -u www-data yarn build"
  tags:
    - local_runner

deploying:
  stage: deploy
  script:
    - "sudo -u www-data pm2 restart energie-be --update-env"
  tags:
    - local_runner
